"""empty message

Revision ID: a53539d4c2cd
Revises: 
Create Date: 2024-05-22 04:05:37.126282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a53539d4c2cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('middle_name')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('middle_name', mysql.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
